/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                  "#0F172A",
        "primary-container":        "#253346",
        "on-primary":               "#FFFFFF",
        "on-primary-container":     "#B2BDCA",
        "secondary":                "#334155",
        "secondary-container":      "#3D5166",
        "on-secondary":             "#FFFFFF",
        "on-secondary-container":   "#CBD5E1",
        "tertiary":                 "#F97316",
        "tertiary-container":       "#C2410C",
        "tertiary-dark":            "#9A3412",
        "on-tertiary":              "#FFFFFF",
        "on-tertiary-container":    "#FFF7ED",
        "tertiary-fixed":           "#FFEDD5",
        "tertiary-fixed-dim":       "#FED7AA",
        "surface":                  "#F8FAFC",
        "surface-bright":           "#F8FAFC",
        "surface-dim":              "#D8DADC",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low":    "#F2F4F6",
        "surface-container":        "#ECEEF0",
        "surface-container-high":   "#E6E8EA",
        "surface-container-highest":"#E0E3E5",
        "surface-variant":          "#E0E3E5",
        "on-surface":               "#191C1E",
        "on-surface-variant":       "#42474F",
        "on-background":            "#191C1E",
        "background":               "#F8FAFC",
        "inverse-surface":          "#2D3133",
        "inverse-on-surface":       "#EFF1F3",
        "inverse-primary":          "#BEC6E0",
        "outline":                  "#727780",
        "outline-variant":          "#C2C7D1",
        "error":                    "#BA1A1A",
        "error-container":          "#FFDAD6",
        "on-error":                 "#FFFFFF",
        "on-error-container":       "#93000A",
        "surface-tint":             "#334155",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
